### ISSUE TITLE
Убедительная просьба!)

### ISSUE THREAD

**Issue by AlexZablotsky450501** [NikolayKovzik450501/Currency#1]
Николай, у вас довольно-таки интересная задумка проекта, который будет очень полезен для людей, которые не достаточно хорошо разбираются в сложных банковских системах, поэтому, убедительная просьба, поскорее добавьте код вашего приложения, чтобы я мог его оценить и подсказать возможные решения некоторых спорных вопросов, которые могли у вас возникнуть в процессе его создания.

**Comment by NikolayKovzik450501** [comment]
Код добавлен.
