### ISSUE TITLE
Стиль кода.

### ISSUE THREAD

**Issue by MarinaTitova** [NikolayKovzik450501/Currency#3]
Николай,

Обычно строка не должна превышать 80 символов (120 при большом разрешении экрана). Длинные строки необходимо разбивать для улучшения читаемости.
Пару названий функций гигантские. Так удобно?)
Комментариев очень мало - разбираться и редактировать будет сложно. Думаю, пояснения пригодятся в будущем:)
В общем код написан достойно, молодец!

**Comment by NikolayKovzik450501** [comment]
Благодарю, все замечания по делу, и в скором времени будут устранены
